name: FMP2

channels:
    - defaults
    - conda-forge

dependencies:
  - python==3.6.5
  - numpy==1.16.4
  - scipy==1.3.1
  - matplotlib==2.0.2
  - ipython==7.7.0
  - jupyter==1.0.0
  - pandas==0.25.1
  - cython==0.28.2
  - scikit-learn==0.21.2
  - ffmpeg==2.8.6
  - numba==0.45.1
  - librosa==0.7.1
  - pip:
    - mir-eval==0.4
    - pysoundfile==0.9.0.post1
    - nbstripout==0.3.3
    - music21==5.7.0
    - pretty_midi==0.2.8
    - jupyter_contrib_nbextensions==0.5.1
